//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace urHealthyDiet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ORDER
    {
        public int ID_ORDER { get; set; }
        public Nullable<int> ID_USER { get; set; }

        [Display(Name = "Name")]
        [Required(ErrorMessage = "You need to give us your name !")]
        public string NAME { get; set; }

        [Display(Name = "Surname")]
        [Required(ErrorMessage = "You need to give us your surname !")]
        public string SURNAME { get; set; }

        [Display(Name = "Address")]
        [Required(ErrorMessage = "You need to give us your address !")]
        public string ADDRESS { get; set; }

        [Display(Name = "City")]
        [Required(ErrorMessage = "You need to give us your city !")]
        public string CITY { get; set; }

        [Display(Name = "Postcode")]
        [Required(ErrorMessage = "You need to give us your post code !")]
        public string POSTCODE { get; set; }

        [Display(Name = "Dietname")]
        [Required(ErrorMessage = "You need to give us your diet name !")]
        public string DIETNAME { get; set; }

        [Display(Name = "Calories")]
        [Required(ErrorMessage = "You need to give us calories !")]
        public Nullable<double> CALORIES { get; set; }

        [Display(Name = "Card number")]
        [Required(ErrorMessage = "You need to give us your card number !")]
        public string CARD_NUM { get; set; }
    }
}
