//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace urHealthyDiet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USER
    {
        public int ID_USER { get; set; }

        [Display(Name = "Login")]
        [Required(ErrorMessage = "You need to give us your login !")]
        public string USER_LOGIN { get; set; }

        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "You must have a password!")]
        [StringLength(100, MinimumLength = 8, ErrorMessage = "You need to provide a long enough password.")]
        public string USER_PASSWORD { get; set; }

        [Display(Name = "User Role")]
        [Required(ErrorMessage = "You need to give your role.")]
        public string ROLE { get; set; }
    }
}
